# Module 1: VN100 Market Data Collection  
This notebook collects historical OHLCV data for the VN100 index constituents.  
- **Source:** Vietnamese stock market data.  
- **Objective:** Build a raw dataset in `.parquet` format to optimize processing performance for subsequent steps.

### 1.1 Library Imports and Project Root Configuration  
We set up the path to enable importing custom functions from the `src` directory.

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import seaborn as sn
import sys
import os
import matplotlib.pyplot as plt
import json
from datetime import date, timedelta

project_root = os.path.abspath("../")

if project_root not in sys.path:
    sys.path.append(project_root)

import src.data_collect as dc

### 1.2 Data Collection Execution  
Use the `src.data_collect` module to retrieve the VN100 ticker list and download OHLCV data.

In [2]:
VN100_tags = dc.build_vn100(fetching=True)

2026-05-12 07:34:07,194  INFO  VN30=30  VNMID=70  VN100=100

In [3]:
print(VN100_tags)

['ACB', 'ANV', 'BCM', 'BID', 'BMP', 'BSI', 'BSR', 'BVH', 'BWE', 'CII', 'CMG', 'CTD', 'CTG', 'CTR', 'CTS', 'DBC', 'DCM', 'DGC', 'DGW', 'DIG', 'DPM', 'DSE', 'DXG', 'DXS', 'EIB', 'EVF', 'FPT', 'FRT', 'FTS', 'GAS', 'GEE', 'GEX', 'GMD', 'GVR', 'HAG', 'HCM', 'HDB', 'HDC', 'HDG', 'HHV', 'HPG', 'HSG', 'HT1', 'IMP', 'KBC', 'KDC', 'KDH', 'KOS', 'LPB', 'MBB', 'MSB', 'MSN', 'MWG', 'NAB', 'NKG', 'NLG', 'NT2', 'NVL', 'OCB', 'PAN', 'PC1', 'PDR', 'PHR', 'PLX', 'PNJ', 'POW', 'PVD', 'PVT', 'REE', 'SAB', 'SBT', 'SCS', 'SHB', 'SIP', 'SJS', 'SSB', 'SSI', 'STB', 'SZC', 'TCB', 'TCH', 'TPB', 'VCB', 'VCG', 'VCI', 'VGC', 'VHC', 'VHM', 'VIB', 'VIC', 'VIX', 'VJC', 'VND', 'VNM', 'VPB', 'VPI', 'VPL', 'VRE', 'VSC', 'VTP']

In [4]:
FILE_PATH = "../compare/market_data_local.parquet"
START_DATE = "2016-01-01"
BATCH_SIZE = 5  # save mỗi 5 mã

dc.update_market_data(
    FILE_PATH,
    VN100_tags,
    START_DATE,
    BATCH_SIZE
)

2026-05-12 07:34:07,891  INFO  → ACB fetching from [VCI]
2026-05-12 07:34:08,615  INFO  ✓ ACB [VCI] — 2705 rows fetched
2026-05-12 07:34:11,624  INFO  → ANV fetching from [VCI]
2026-05-12 07:34:12,210  INFO  ✓ ANV [VCI] — 2705 rows fetched
2026-05-12 07:34:15,214  INFO  → BCM fetching from [VCI]
2026-05-12 07:34:15,721  INFO  ✓ BCM [VCI] — 2044 rows fetched
2026-05-12 07:34:18,731  INFO  → BID fetching from [VCI]
2026-05-12 07:34:19,198  INFO  ✓ BID [VCI] — 2705 rows fetched
2026-05-12 07:34:22,207  INFO  → BMP fetching from [VCI]
2026-05-12 07:34:22,697  INFO  ✓ BMP [VCI] — 2705 rows fetched
2026-05-12 07:34:25,725  INFO  🧹 Zero-volume trim: dropped 2037 rows across 4 symbol(s)
2026-05-12 07:34:25,859  INFO  💾 Batch save at 5 symbols (10334 total rows)
2026-05-12 07:34:25,891  INFO  → BSI fetching from [VCI]
2026-05-12 07:34:26,415  INFO  ✓ BSI [VCI] — 2705 rows fetched
2026-05-12 07:34:29,423  INFO  → BSR fetching from [VCI]
2026-05-12 07:34:30,048  INFO  ✓ BSR [VCI] — 2037 rows fetched
2026-05-12 07:34:33,057  INFO  → BVH fetching from [VCI]
2026-05-12 07:34:33,542  INFO  ✓ BVH [VCI] — 2705 rows fetched
2026-05-12 07:34:36,554  INFO  → BWE fetching from [VCI]
2026-05-12 07:34:37,016  INFO  ✓ BWE [VCI] — 2198 rows fetched
2026-05-12 07:34:40,024  INFO  → CII fetching from [VCI]
2026-05-12 07:34:40,558  INFO  ✓ CII [VCI] — 2705 rows fetched
2026-05-12 07:34:43,590  INFO  🧹 Zero-volume trim: dropped 1687 rows across 4 symbol(s)
2026-05-12 07:34:43,615  INFO  💾 Batch save at 10 symbols (20625 total rows)
2026-05-12 07:34:43,623  INFO  → CMG fetching from [VCI]
2026-05-12 07:34:44,123  INFO  ✓ CMG [VCI] — 2705 rows fetched
2026-05-12 07:34:47,139  INFO  → CTD fetching from [VCI]
2026-05-12 07:34:47,643  INFO  ✓ CTD [VCI] — 2705 rows fetched
2026-05-12 07:34:50,658  INFO  → CTG fetching from [VCI]
2026-05-12 07:34:51,159  INFO  ✓ CTG [VCI] — 2705 rows fetched
2026-05-12 07:34:54,173  INFO  → CTR fetching from [VCI]
2026-05-12 07:34:54,621  INFO  ✓ CTR [VCI] — 2125 rows fetched
2026-05-12 07:34:57,642  INFO  → CTS fetching from [VCI]
2026-05-12 07:34:58,239  INFO  ✓ CTS [VCI] — 2705 rows fetched
2026-05-12 07:35:01,268  INFO  🧹 Zero-volume trim: dropped 2287 rows across 5 symbol(s)
2026-05-12 07:35:01,300  INFO  💾 Batch save at 15 symbols (30792 total rows)
2026-05-12 07:35:01,300  INFO  → DBC fetching from [VCI]
2026-05-12 07:35:01,909  INFO  ✓ DBC [VCI] — 2705 rows fetched
2026-05-12 07:35:04,913  INFO  → DCM fetching from [VCI]
2026-05-12 07:35:05,444  INFO  ✓ DCM [VCI] — 2705 rows fetched
2026-05-12 07:35:08,458  INFO  → DGC fetching from [VCI]
2026-05-12 07:35:08,941  INFO  ✓ DGC [VCI] — 2705 rows fetched
2026-05-12 07:35:11,957  INFO  → DGW fetching from [VCI]
2026-05-12 07:35:12,732  INFO  ✓ DGW [VCI] — 2691 rows fetched
2026-05-12 07:35:15,745  INFO  → DIG fetching from [VCI]
2026-05-12 07:35:16,540  INFO  ✓ DIG [VCI] — 2705 rows fetched
2026-05-12 07:35:19,556  INFO  🧹 Zero-volume trim: dropped 1554 rows across 3 symbol(s)
2026-05-12 07:35:19,603  INFO  💾 Batch save at 20 symbols (42141 total rows)
2026-05-12 07:35:19,603  INFO  → DPM fetching from [VCI]
2026-05-12 07:35:20,119  INFO  ✓ DPM [VCI] — 2705 rows fetched
2026-05-12 07:35:23,132  INFO  → DSE fetching from [VCI]
2026-05-12 07:35:23,487  INFO  ✓ DSE [VCI] — 462 rows fetched
2026-05-12 07:35:26,496  INFO  → DXG fetching from [VCI]
2026-05-12 07:35:26,964  INFO  ✓ DXG [VCI] — 2705 rows fetched
2026-05-12 07:35:29,987  INFO  → DXS fetching from [VCI]
2026-05-12 07:35:30,402  INFO  ✓ DXS [VCI] — 1197 rows fetched
2026-05-12 07:35:33,406  INFO  → EIB fetching from [VCI]
2026-05-12 07:35:33,874  INFO  ✓ EIB [VCI] — 2705 rows fetched
2026-05-12 07:35:36,911  INFO  🧹 Zero-volume trim: dropped 1554 rows across 3 symbol(s)
2026-05-12 07:35:36,994  INFO  💾 Batch save at 25 symbols (49995 total rows)
2026-05-12 07:35:37,000  INFO  → EVF fetching from [VCI]
2026-05-12 07:35:37,475  INFO  ✓ EVF [VCI] — 1927 rows fetched
2026-05-12 07:35:40,485  INFO  → FPT fetching from [VCI]
2026-05-12 07:35:41,026  INFO  ✓ FPT [VCI] — 2705 rows fetched
2026-05-12 07:35:44,038  INFO  → FRT fetching from [VCI]
2026-05-12 07:35:44,476  INFO  ✓ FRT [VCI] — 2006 rows fetched
2026-05-12 07:35:47,484  INFO  → FTS fetching from [VCI]
2026-05-12 07:35:47,978  INFO  ✓ FTS [VCI] — 2324 rows fetched
2026-05-12 07:35:50,988  INFO  → GAS fetching from [VCI]
2026-05-12 07:35:51,468  INFO  ✓ GAS [VCI] — 2705 rows fetched
2026-05-12 07:35:54,513  INFO  🧹 Zero-volume trim: dropped 1586 rows across 4 symbol(s)
2026-05-12 07:35:54,576  INFO  💾 Batch save at 30 symbols (59832 total rows)
2026-05-12 07:35:54,576  INFO  → GEE fetching from [VCI]
2026-05-12 07:35:55,039  INFO  ✓ GEE [VCI] — 1022 rows fetched
2026-05-12 07:35:58,042  INFO  → GEX fetching from [VCI]
2026-05-12 07:35:58,552  INFO  ✓ GEX [VCI] — 2629 rows fetched
2026-05-12 07:36:01,568  INFO  → GMD fetching from [VCI]
2026-05-12 07:36:02,056  INFO  ✓ GMD [VCI] — 2705 rows fetched
2026-05-12 07:36:05,061  INFO  → GVR fetching from [VCI]
2026-05-12 07:36:05,503  INFO  ✓ GVR [VCI] — 2025 rows fetched
2026-05-12 07:36:08,510  INFO  → HAG fetching from [VCI]
2026-05-12 07:36:08,913  INFO  ✓ HAG [VCI] — 2705 rows fetched
2026-05-12 07:36:11,960  INFO  🧹 Zero-volume trim: dropped 2081 rows across 4 symbol(s)
2026-05-12 07:36:12,022  INFO  💾 Batch save at 35 symbols (68544 total rows)
2026-05-12 07:36:12,038  INFO  → HCM fetching from [VCI]
2026-05-12 07:36:12,389  INFO  ✓ HCM [VCI] — 2705 rows fetched
2026-05-12 07:36:15,397  INFO  → HDB fetching from [VCI]
2026-05-12 07:36:15,757  INFO  ✓ HDB [VCI] — 2079 rows fetched
2026-05-12 07:36:18,759  INFO  → HDC fetching from [VCI]
2026-05-12 07:36:19,056  INFO  ✓ HDC [VCI] — 2705 rows fetched
2026-05-12 07:36:22,060  INFO  → HDG fetching from [VCI]
2026-05-12 07:36:22,321  INFO  ✓ HDG [VCI] — 2705 rows fetched
2026-05-12 07:36:25,359  INFO  → HHV fetching from [VCI]
2026-05-12 07:36:25,694  INFO  ✓ HHV [VCI] — 2584 rows fetched
2026-05-12 07:36:28,746  INFO  🧹 Zero-volume trim: dropped 2917 rows across 5 symbol(s)
2026-05-12 07:36:28,825  INFO  💾 Batch save at 40 symbols (78029 total rows)
2026-05-12 07:36:28,825  INFO  → HPG fetching from [VCI]
2026-05-12 07:36:29,160  INFO  ✓ HPG [VCI] — 2705 rows fetched
2026-05-12 07:36:32,170  INFO  → HSG fetching from [VCI]
2026-05-12 07:36:32,435  INFO  ✓ HSG [VCI] — 2705 rows fetched
2026-05-12 07:36:35,437  INFO  → HT1 fetching from [VCI]
2026-05-12 07:36:36,077  INFO  ✓ HT1 [VCI] — 2705 rows fetched
2026-05-12 07:36:39,086  INFO  → IMP fetching from [VCI]
2026-05-12 07:36:39,452  INFO  ✓ IMP [VCI] — 2705 rows fetched
2026-05-12 07:36:42,457  INFO  → KBC fetching from [VCI]
2026-05-12 07:36:42,754  INFO  ✓ KBC [VCI] — 2705 rows fetched
2026-05-12 07:36:45,805  INFO  🧹 Zero-volume trim: dropped 3822 rows across 5 symbol(s)
2026-05-12 07:36:45,886  INFO  💾 Batch save at 45 symbols (87122 total rows)
2026-05-12 07:36:45,886  INFO  → KDC fetching from [VCI]
2026-05-12 07:36:46,220  INFO  ✓ KDC [VCI] — 2705 rows fetched
2026-05-12 07:36:49,221  INFO  → KDH fetching from [VCI]
2026-05-12 07:36:49,476  INFO  ✓ KDH [VCI] — 2705 rows fetched
2026-05-12 07:36:52,488  INFO  → KOS fetching from [VCI]
2026-05-12 07:36:52,733  INFO  ✓ KOS [VCI] — 2093 rows fetched
2026-05-12 07:36:55,742  INFO  → LPB fetching from [VCI]
2026-05-12 07:36:55,960  INFO  ✓ LPB [VCI] — 2134 rows fetched
2026-05-12 07:36:58,962  INFO  → MBB fetching from [VCI]
2026-05-12 07:36:59,265  INFO  ✓ MBB [VCI] — 2705 rows fetched
2026-05-12 07:37:02,329  INFO  🧹 Zero-volume trim: dropped 1554 rows across 3 symbol(s)
2026-05-12 07:37:02,425  INFO  💾 Batch save at 50 symbols (97544 total rows)
2026-05-12 07:37:02,425  INFO  → MSB fetching from [VCI]
2026-05-12 07:37:02,619  INFO  ✓ MSB [VCI] — 1337 rows fetched
2026-05-12 07:37:05,625  INFO  → MSN fetching from [VCI]
2026-05-12 07:37:05,875  INFO  ✓ MSN [VCI] — 2705 rows fetched
2026-05-12 07:37:08,888  INFO  → MWG fetching from [VCI]
2026-05-12 07:37:09,200  INFO  ✓ MWG [VCI] — 2705 rows fetched
2026-05-12 07:37:12,211  INFO  → NAB fetching from [VCI]
2026-05-12 07:37:12,445  INFO  ✓ NAB [VCI] — 1384 rows fetched
2026-05-12 07:37:15,461  INFO  → NKG fetching from [VCI]
2026-05-12 07:37:15,695  INFO  ✓ NKG [VCI] — 2705 rows fetched
2026-05-12 07:37:18,779  INFO  🧹 Zero-volume trim: dropped 1554 rows across 3 symbol(s)
2026-05-12 07:37:18,879  INFO  💾 Batch save at 55 symbols (106460 total rows)
2026-05-12 07:37:18,879  INFO  → NLG fetching from [VCI]
2026-05-12 07:37:19,162  INFO  ✓ NLG [VCI] — 2705 rows fetched
2026-05-12 07:37:22,178  INFO  → NT2 fetching from [VCI]
2026-05-12 07:37:22,445  INFO  ✓ NT2 [VCI] — 2705 rows fetched
2026-05-12 07:37:25,456  INFO  → NVL fetching from [VCI]
2026-05-12 07:37:25,667  INFO  ✓ NVL [VCI] — 2335 rows fetched
2026-05-12 07:37:28,678  INFO  → OCB fetching from [VCI]
2026-05-12 07:37:28,873  INFO  ✓ OCB [VCI] — 1312 rows fetched
2026-05-12 07:37:31,878  INFO  → PAN fetching from [VCI]
2026-05-12 07:37:32,139  INFO  ✓ PAN [VCI] — 2705 rows fetched
2026-05-12 07:37:35,229  INFO  🧹 Zero-volume trim: dropped 1824 rows across 4 symbol(s)
2026-05-12 07:37:35,330  INFO  💾 Batch save at 60 symbols (116025 total rows)
2026-05-12 07:37:35,330  INFO  → PC1 fetching from [VCI]
2026-05-12 07:37:35,603  INFO  ✓ PC1 [VCI] — 2365 rows fetched
2026-05-12 07:37:38,612  INFO  → PDR fetching from [VCI]
2026-05-12 07:37:38,929  INFO  ✓ PDR [VCI] — 2705 rows fetched
2026-05-12 07:37:41,944  INFO  → PHR fetching from [VCI]
2026-05-12 07:37:42,212  INFO  ✓ PHR [VCI] — 2705 rows fetched
2026-05-12 07:37:45,228  INFO  → PLX fetching from [VCI]
2026-05-12 07:37:45,495  INFO  ✓ PLX [VCI] — 2260 rows fetched
2026-05-12 07:37:48,496  INFO  → PNJ fetching from [VCI]
2026-05-12 07:37:48,746  INFO  ✓ PNJ [VCI] — 2705 rows fetched
2026-05-12 07:37:51,832  INFO  🧹 Zero-volume trim: dropped 2049 rows across 5 symbol(s)
2026-05-12 07:37:51,946  INFO  💾 Batch save at 65 symbols (126350 total rows)
2026-05-12 07:37:51,946  INFO  → POW fetching from [VCI]
2026-05-12 07:37:52,213  INFO  ✓ POW [VCI] — 2033 rows fetched
2026-05-12 07:37:55,229  INFO  → PVD fetching from [VCI]
2026-05-12 07:37:55,546  INFO  ✓ PVD [VCI] — 2705 rows fetched
2026-05-12 07:37:58,563  INFO  → PVT fetching from [VCI]
2026-05-12 07:37:58,863  INFO  ✓ PVT [VCI] — 2705 rows fetched
2026-05-12 07:38:01,879  INFO  → REE fetching from [VCI]
2026-05-12 07:38:02,166  INFO  ✓ REE [VCI] — 2705 rows fetched
2026-05-12 07:38:05,174  INFO  → SAB fetching from [VCI]
2026-05-12 07:38:05,482  INFO  ✓ SAB [VCI] — 2351 rows fetched
2026-05-12 07:38:08,565  INFO  🧹 Zero-volume trim: dropped 1840 rows across 4 symbol(s)
2026-05-12 07:38:08,694  INFO  💾 Batch save at 70 symbols (136643 total rows)
2026-05-12 07:38:08,694  INFO  → SBT fetching from [VCI]
2026-05-12 07:38:09,090  INFO  ✓ SBT [VCI] — 2705 rows fetched
2026-05-12 07:38:12,101  INFO  → SCS fetching from [VCI]
2026-05-12 07:38:12,433  INFO  ✓ SCS [VCI] — 2198 rows fetched
2026-05-12 07:38:15,447  INFO  → SHB fetching from [VCI]
2026-05-12 07:38:15,930  INFO  ✓ SHB [VCI] — 2705 rows fetched
2026-05-12 07:38:18,947  INFO  → SIP fetching from [VCI]
2026-05-12 07:38:19,248  INFO  ✓ SIP [VCI] — 1725 rows fetched
2026-05-12 07:38:22,264  INFO  → SJS fetching from [VCI]
2026-05-12 07:38:22,566  INFO  ✓ SJS [VCI] — 2705 rows fetched
2026-05-12 07:38:25,666  INFO  🧹 Zero-volume trim: dropped 1506 rows across 4 symbol(s)
2026-05-12 07:38:25,781  INFO  💾 Batch save at 75 symbols (146806 total rows)
2026-05-12 07:38:25,781  INFO  → SSB fetching from [VCI]
2026-05-12 07:38:25,983  INFO  ✓ SSB [VCI] — 1278 rows fetched
2026-05-12 07:38:28,997  INFO  → SSI fetching from [VCI]
2026-05-12 07:38:29,266  INFO  ✓ SSI [VCI] — 2705 rows fetched
2026-05-12 07:38:32,279  INFO  → STB fetching from [VCI]
2026-05-12 07:38:32,731  INFO  ✓ STB [VCI] — 2705 rows fetched
2026-05-12 07:38:35,747  INFO  → SZC fetching from [VCI]
2026-05-12 07:38:36,167  INFO  ✓ SZC [VCI] — 1823 rows fetched
2026-05-12 07:38:39,174  INFO  → TCB fetching from [VCI]
2026-05-12 07:38:39,467  INFO  ✓ TCB [VCI] — 1981 rows fetched
2026-05-12 07:38:42,564  INFO  🧹 Zero-volume trim: dropped 1036 rows across 2 symbol(s)
2026-05-12 07:38:42,714  INFO  💾 Batch save at 80 symbols (156018 total rows)
2026-05-12 07:38:42,714  INFO  → TCH fetching from [VCI]
2026-05-12 07:38:42,979  INFO  ✓ TCH [VCI] — 2395 rows fetched
2026-05-12 07:38:45,982  INFO  → TPB fetching from [VCI]
2026-05-12 07:38:46,231  INFO  ✓ TPB [VCI] — 2010 rows fetched
2026-05-12 07:38:49,247  INFO  → VCB fetching from [VCI]
2026-05-12 07:38:49,568  INFO  ✓ VCB [VCI] — 2705 rows fetched
2026-05-12 07:38:52,576  INFO  → VCG fetching from [VCI]
2026-05-12 07:38:53,048  INFO  ✓ VCG [VCI] — 2705 rows fetched
2026-05-12 07:38:56,062  INFO  → VCI fetching from [VCI]
2026-05-12 07:38:56,298  INFO  ✓ VCI [VCI] — 2207 rows fetched
2026-05-12 07:38:59,401  INFO  🧹 Zero-volume trim: dropped 990 rows across 3 symbol(s)
2026-05-12 07:38:59,565  INFO  💾 Batch save at 85 symbols (166801 total rows)
2026-05-12 07:38:59,565  INFO  → VGC fetching from [VCI]
2026-05-12 07:38:59,834  INFO  ✓ VGC [VCI] — 2628 rows fetched
2026-05-12 07:39:02,848  INFO  → VHC fetching from [VCI]
2026-05-12 07:39:03,231  INFO  ✓ VHC [VCI] — 2705 rows fetched
2026-05-12 07:39:06,248  INFO  → VHM fetching from [VCI]
2026-05-12 07:39:06,465  INFO  ✓ VHM [VCI] — 2705 rows fetched
2026-05-12 07:39:09,482  INFO  → VIB fetching from [VCI]
2026-05-12 07:39:09,732  INFO  ✓ VIB [VCI] — 2321 rows fetched
2026-05-12 07:39:12,748  INFO  → VIC fetching from [VCI]
2026-05-12 07:39:13,010  INFO  ✓ VIC [VCI] — 2705 rows fetched
2026-05-12 07:39:16,115  INFO  🧹 Zero-volume trim: dropped 1589 rows across 5 symbol(s)
2026-05-12 07:39:16,265  INFO  💾 Batch save at 90 symbols (177645 total rows)
2026-05-12 07:39:16,265  INFO  → VIX fetching from [VCI]
2026-05-12 07:39:16,565  INFO  ✓ VIX [VCI] — 2705 rows fetched
2026-05-12 07:39:19,582  INFO  → VJC fetching from [VCI]
2026-05-12 07:39:19,834  INFO  ✓ VJC [VCI] — 2297 rows fetched
2026-05-12 07:39:22,848  INFO  → VND fetching from [VCI]
2026-05-12 07:39:23,099  INFO  ✓ VND [VCI] — 2705 rows fetched
2026-05-12 07:39:26,107  INFO  → VNM fetching from [VCI]
2026-05-12 07:39:26,399  INFO  ✓ VNM [VCI] — 2705 rows fetched
2026-05-12 07:39:29,412  INFO  → VPB fetching from [VCI]
2026-05-12 07:39:29,668  INFO  ✓ VPB [VCI] — 2178 rows fetched
2026-05-12 07:39:32,785  INFO  🧹 Zero-volume trim: dropped 2233 rows across 5 symbol(s)
2026-05-12 07:39:32,949  INFO  💾 Batch save at 95 symbols (187619 total rows)
2026-05-12 07:39:32,949  INFO  → VPI fetching from [VCI]
2026-05-12 07:39:33,266  INFO  ✓ VPI [VCI] — 2099 rows fetched
2026-05-12 07:39:36,266  INFO  → VPL fetching from [VCI]
2026-05-12 07:39:36,518  INFO  ✓ VPL [VCI] — 248 rows fetched
2026-05-12 07:39:39,532  INFO  → VRE fetching from [VCI]
2026-05-12 07:39:39,766  INFO  ✓ VRE [VCI] — 2122 rows fetched
2026-05-12 07:39:42,782  INFO  → VSC fetching from [VCI]
2026-05-12 07:39:43,083  INFO  ✓ VSC [VCI] — 2705 rows fetched
2026-05-12 07:39:46,099  INFO  → VTP fetching from [VCI]
2026-05-12 07:39:46,383  INFO  ✓ VTP [VCI] — 1851 rows fetched
2026-05-12 07:39:49,499  INFO  🧹 Zero-volume trim: dropped 575 rows across 2 symbol(s)
2026-05-12 07:39:49,669  INFO  💾 Batch save at 100 symbols (195947 total rows)

In [5]:
df = pd.read_parquet(FILE_PATH)
df.tail(5)

             date  open  high   low  close   volume Symbol
195942 2026-05-05  67.9  68.0  65.4   65.9  1010300    VTP
195943 2026-05-06  66.1  66.4  65.5   66.4   427900    VTP
195944 2026-05-07  66.7  67.6  65.7   66.2   515400    VTP
195945 2026-05-08  66.4  66.4  65.5   66.0   340100    VTP
195946 2026-05-11  66.0  66.0  62.9   63.2   849400    VTP

# VNINDEX

In [3]:
FILE_PATH = "../data/vnindex_data.parquet"
START_DATE = "2016-01-01"
dc.fetch_indicator_data(
    ind_symbol="VNINDEX", 
    start_date=START_DATE, 
    file_path=FILE_PATH
)

2026-05-14 14:59:35,177  INFO  → VNINDEX fetching from [VCI]

2026-05-14 14:59:37,096  INFO  ✓ VNINDEX [VCI] — 2707 rows saved to ../data/vnindex_data.parquet

In [4]:
df = pd.read_parquet(FILE_PATH)
df.head()

        date    open    high     low   close     volume
0 2015-07-15  640.43  641.06  630.89  630.89  135994360
1 2015-07-16  627.32  632.21  622.57  626.90  113628750
2 2015-07-17  628.45  631.67  626.21  628.63   97179130
3 2015-07-20  624.84  624.84  616.11  620.54  105000850
4 2015-07-21  619.90  624.47  613.83  616.61   95668300